defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

metric: f1
model_type: null
copy_to_resources: true
sizes: null

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: ''
