name: knapsack
n_objs: 4
n_vars: 50
size: ${prob.n_objs}_${prob.n_vars}

order_type: MinWt
preprocess: true
pf_enum_method: 1
maximization: true
dominance: 0
track_x: 1
bdd_type: 0
maxwidth: 0
layer_norm_const: 100
state_norm_const: 1000
